//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""NewPlayerControls"",
            ""id"": ""68c4e1cb-6795-47f6-81ca-cd0133bc12ef"",
            ""actions"": [
                {
                    ""name"": ""AccelerationDeceleration"",
                    ""type"": ""PassThrough"",
                    ""id"": ""c93b84b0-a0e8-478c-9598-d0e986e0b277"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a07e8753-f8a3-42c3-80ca-998cae99b47a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5b289202-df47-4533-a5b7-fc00fa39ec87"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AscendDescent"",
                    ""type"": ""PassThrough"",
                    ""id"": ""6df46191-03e0-477a-8c12-14dc54e446fe"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryFire"",
                    ""type"": ""Button"",
                    ""id"": ""bc986f9e-c01a-4de3-b81a-136fe6481628"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShootFlare"",
                    ""type"": ""Button"",
                    ""id"": ""7878b65f-eec6-4915-aa76-1334594fa40a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectLaserGun"",
                    ""type"": ""Button"",
                    ""id"": ""6716072c-0ea8-44fe-be94-017f2a2ae46f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectVulcanGun"",
                    ""type"": ""Button"",
                    ""id"": ""da851fa7-753f-4762-bc4b-f9345509dd70"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectConcussionMissile"",
                    ""type"": ""Button"",
                    ""id"": ""64d1ae4c-29b6-4a8b-9bc7-64ecff88eb45"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectHomingMissile"",
                    ""type"": ""Button"",
                    ""id"": ""aed2f768-7ebb-4b16-bfb4-ce4528d0a95d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryFire"",
                    ""type"": ""Button"",
                    ""id"": ""0854aeda-4f74-40a5-89c6-4ddccd6ca905"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""f1a4bb00-0504-4000-a172-b8b989b6bc03"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AccelerationDeceleration"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5e1ec130-5989-4bc8-b10c-8cef6f240854"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AccelerationDeceleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6ea3ae28-025f-4412-bbf7-efba507d2789"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AccelerationDeceleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4290daf6-9438-4ec2-8fad-4083e63e690a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AccelerationDeceleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""93b70671-6d5d-4644-a704-bc3cfdf7b9e7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AccelerationDeceleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""9c868c60-f759-467c-8f64-9d7d37fd2dc1"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b7dfa792-fbda-458e-bbdd-ade222bae698"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4250227d-0069-4b9e-a49a-cb0959a4338d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""eae72178-7a9e-4c27-aaf2-2b9442b382ea"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""c29286f5-d428-4410-a844-4ab44cbcc494"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AscendDescent"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2ec9fe96-551e-4384-acab-0a0cfdb80a10"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AscendDescent"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0302f060-ec13-497a-af83-eb72c315a042"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AscendDescent"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b49b3266-dfdf-4d30-989c-87a91345fff7"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryFire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f0cf9e5-a970-4d88-b144-77b2455a5512"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShootFlare"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43c0f57e-955c-48b0-bf80-6f6cb015895f"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectLaserGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c41ee0d-985e-461f-91a6-896bc4f0263d"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectLaserGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62895d78-5a56-43cb-a748-2f0c7a376f57"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectVulcanGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e94d6b2c-6ec2-4d6d-91f1-1630c4200e1a"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectVulcanGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b56ee9a3-d89c-4947-b463-ff5844d159b3"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectConcussionMissile"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61a2dbcf-f7ef-4527-839f-e88b5a2d34d9"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectHomingMissile"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a880a775-6ff5-400d-aa59-82256bd4eef5"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryFire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""OldPlayerControls"",
            ""id"": ""d9693513-2307-4035-8133-1f53f287a5da"",
            ""actions"": [
                {
                    ""name"": ""AccelerationDeceleration"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7f7cfb6e-88e9-43f4-bf0d-7b4b714db794"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ef3324bd-a443-4ee7-a77b-1feced7f416c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d4e3972e-2686-4787-80c8-69e5321995ff"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryFire"",
                    ""type"": ""Button"",
                    ""id"": ""72659ec1-c4f4-42f5-bbd1-abeda51e06ac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShootFlare"",
                    ""type"": ""Button"",
                    ""id"": ""0aeeb17c-a490-4318-ba87-413bb702caed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectLaserGun"",
                    ""type"": ""Button"",
                    ""id"": ""4fdde084-0b32-417a-803b-7a48fccfb3c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectVulkanGun"",
                    ""type"": ""Button"",
                    ""id"": ""4465e423-6474-4093-94d2-54ea37fbcc16"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectConcussionMissile"",
                    ""type"": ""Button"",
                    ""id"": ""d9f78071-87b7-432c-9082-7d93b8f5936d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectHomingMissile"",
                    ""type"": ""Button"",
                    ""id"": ""a7e35442-5106-4501-9490-798b83c9ca3a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryFire"",
                    ""type"": ""Button"",
                    ""id"": ""13cbca9c-df42-4505-b85e-a67efbe12c5b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""AZ"",
                    ""id"": ""3a32137f-2525-4515-a15b-64b46a50af2b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AccelerationDeceleration"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0e929935-b17b-453c-a5ee-cae8d7968bd7"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AccelerationDeceleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""256595cc-cdf1-4451-9849-dd109f640bb1"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AccelerationDeceleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""QE"",
                    ""id"": ""2ea23034-fd49-4812-a55a-7b53c47b9601"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2108c375-3fc0-43db-8dcf-8c08dbd55887"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e991b850-c7c8-4bdb-9df9-91d46c4ef8f9"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""cfa97fa0-634f-4572-b04d-96cb1d8d41b1"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6ec68dfa-f853-42eb-ae44-2a8e7e04960d"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""65fb8379-0a80-4173-b115-ff1c9d241199"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""38cbf303-320c-434b-912a-5450509b4faf"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d34c6962-bdeb-4174-a19b-d3a2b740168a"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1e70d26a-fdd7-4cc7-884e-427dc86a47fd"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryFire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a291b084-a314-4c3b-ba5e-ff09e5a34ed2"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShootFlare"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3948f1b3-59bf-4135-84dc-48c3b230ca1a"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectLaserGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e31e33e3-ae65-45e1-b2a8-8ecddabf4522"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectVulkanGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c15cd48-9a2f-4216-97b7-5330e48f9138"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectConcussionMissile"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbfe7a07-69ed-4e4c-bd81-d58079f60ef0"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectHomingMissile"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c8fd43a6-332c-4252-bb1b-cbff38b81e2d"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryFire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // NewPlayerControls
        m_NewPlayerControls = asset.FindActionMap("NewPlayerControls", throwIfNotFound: true);
        m_NewPlayerControls_AccelerationDeceleration = m_NewPlayerControls.FindAction("AccelerationDeceleration", throwIfNotFound: true);
        m_NewPlayerControls_Rotation = m_NewPlayerControls.FindAction("Rotation", throwIfNotFound: true);
        m_NewPlayerControls_Look = m_NewPlayerControls.FindAction("Look", throwIfNotFound: true);
        m_NewPlayerControls_AscendDescent = m_NewPlayerControls.FindAction("AscendDescent", throwIfNotFound: true);
        m_NewPlayerControls_PrimaryFire = m_NewPlayerControls.FindAction("PrimaryFire", throwIfNotFound: true);
        m_NewPlayerControls_ShootFlare = m_NewPlayerControls.FindAction("ShootFlare", throwIfNotFound: true);
        m_NewPlayerControls_SelectLaserGun = m_NewPlayerControls.FindAction("SelectLaserGun", throwIfNotFound: true);
        m_NewPlayerControls_SelectVulcanGun = m_NewPlayerControls.FindAction("SelectVulcanGun", throwIfNotFound: true);
        m_NewPlayerControls_SelectConcussionMissile = m_NewPlayerControls.FindAction("SelectConcussionMissile", throwIfNotFound: true);
        m_NewPlayerControls_SelectHomingMissile = m_NewPlayerControls.FindAction("SelectHomingMissile", throwIfNotFound: true);
        m_NewPlayerControls_SecondaryFire = m_NewPlayerControls.FindAction("SecondaryFire", throwIfNotFound: true);
        // OldPlayerControls
        m_OldPlayerControls = asset.FindActionMap("OldPlayerControls", throwIfNotFound: true);
        m_OldPlayerControls_AccelerationDeceleration = m_OldPlayerControls.FindAction("AccelerationDeceleration", throwIfNotFound: true);
        m_OldPlayerControls_Rotation = m_OldPlayerControls.FindAction("Rotation", throwIfNotFound: true);
        m_OldPlayerControls_Look = m_OldPlayerControls.FindAction("Look", throwIfNotFound: true);
        m_OldPlayerControls_PrimaryFire = m_OldPlayerControls.FindAction("PrimaryFire", throwIfNotFound: true);
        m_OldPlayerControls_ShootFlare = m_OldPlayerControls.FindAction("ShootFlare", throwIfNotFound: true);
        m_OldPlayerControls_SelectLaserGun = m_OldPlayerControls.FindAction("SelectLaserGun", throwIfNotFound: true);
        m_OldPlayerControls_SelectVulkanGun = m_OldPlayerControls.FindAction("SelectVulkanGun", throwIfNotFound: true);
        m_OldPlayerControls_SelectConcussionMissile = m_OldPlayerControls.FindAction("SelectConcussionMissile", throwIfNotFound: true);
        m_OldPlayerControls_SelectHomingMissile = m_OldPlayerControls.FindAction("SelectHomingMissile", throwIfNotFound: true);
        m_OldPlayerControls_SecondaryFire = m_OldPlayerControls.FindAction("SecondaryFire", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // NewPlayerControls
    private readonly InputActionMap m_NewPlayerControls;
    private List<INewPlayerControlsActions> m_NewPlayerControlsActionsCallbackInterfaces = new List<INewPlayerControlsActions>();
    private readonly InputAction m_NewPlayerControls_AccelerationDeceleration;
    private readonly InputAction m_NewPlayerControls_Rotation;
    private readonly InputAction m_NewPlayerControls_Look;
    private readonly InputAction m_NewPlayerControls_AscendDescent;
    private readonly InputAction m_NewPlayerControls_PrimaryFire;
    private readonly InputAction m_NewPlayerControls_ShootFlare;
    private readonly InputAction m_NewPlayerControls_SelectLaserGun;
    private readonly InputAction m_NewPlayerControls_SelectVulcanGun;
    private readonly InputAction m_NewPlayerControls_SelectConcussionMissile;
    private readonly InputAction m_NewPlayerControls_SelectHomingMissile;
    private readonly InputAction m_NewPlayerControls_SecondaryFire;
    public struct NewPlayerControlsActions
    {
        private @PlayerControls m_Wrapper;
        public NewPlayerControlsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @AccelerationDeceleration => m_Wrapper.m_NewPlayerControls_AccelerationDeceleration;
        public InputAction @Rotation => m_Wrapper.m_NewPlayerControls_Rotation;
        public InputAction @Look => m_Wrapper.m_NewPlayerControls_Look;
        public InputAction @AscendDescent => m_Wrapper.m_NewPlayerControls_AscendDescent;
        public InputAction @PrimaryFire => m_Wrapper.m_NewPlayerControls_PrimaryFire;
        public InputAction @ShootFlare => m_Wrapper.m_NewPlayerControls_ShootFlare;
        public InputAction @SelectLaserGun => m_Wrapper.m_NewPlayerControls_SelectLaserGun;
        public InputAction @SelectVulcanGun => m_Wrapper.m_NewPlayerControls_SelectVulcanGun;
        public InputAction @SelectConcussionMissile => m_Wrapper.m_NewPlayerControls_SelectConcussionMissile;
        public InputAction @SelectHomingMissile => m_Wrapper.m_NewPlayerControls_SelectHomingMissile;
        public InputAction @SecondaryFire => m_Wrapper.m_NewPlayerControls_SecondaryFire;
        public InputActionMap Get() { return m_Wrapper.m_NewPlayerControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(NewPlayerControlsActions set) { return set.Get(); }
        public void AddCallbacks(INewPlayerControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_NewPlayerControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_NewPlayerControlsActionsCallbackInterfaces.Add(instance);
            @AccelerationDeceleration.started += instance.OnAccelerationDeceleration;
            @AccelerationDeceleration.performed += instance.OnAccelerationDeceleration;
            @AccelerationDeceleration.canceled += instance.OnAccelerationDeceleration;
            @Rotation.started += instance.OnRotation;
            @Rotation.performed += instance.OnRotation;
            @Rotation.canceled += instance.OnRotation;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @AscendDescent.started += instance.OnAscendDescent;
            @AscendDescent.performed += instance.OnAscendDescent;
            @AscendDescent.canceled += instance.OnAscendDescent;
            @PrimaryFire.started += instance.OnPrimaryFire;
            @PrimaryFire.performed += instance.OnPrimaryFire;
            @PrimaryFire.canceled += instance.OnPrimaryFire;
            @ShootFlare.started += instance.OnShootFlare;
            @ShootFlare.performed += instance.OnShootFlare;
            @ShootFlare.canceled += instance.OnShootFlare;
            @SelectLaserGun.started += instance.OnSelectLaserGun;
            @SelectLaserGun.performed += instance.OnSelectLaserGun;
            @SelectLaserGun.canceled += instance.OnSelectLaserGun;
            @SelectVulcanGun.started += instance.OnSelectVulcanGun;
            @SelectVulcanGun.performed += instance.OnSelectVulcanGun;
            @SelectVulcanGun.canceled += instance.OnSelectVulcanGun;
            @SelectConcussionMissile.started += instance.OnSelectConcussionMissile;
            @SelectConcussionMissile.performed += instance.OnSelectConcussionMissile;
            @SelectConcussionMissile.canceled += instance.OnSelectConcussionMissile;
            @SelectHomingMissile.started += instance.OnSelectHomingMissile;
            @SelectHomingMissile.performed += instance.OnSelectHomingMissile;
            @SelectHomingMissile.canceled += instance.OnSelectHomingMissile;
            @SecondaryFire.started += instance.OnSecondaryFire;
            @SecondaryFire.performed += instance.OnSecondaryFire;
            @SecondaryFire.canceled += instance.OnSecondaryFire;
        }

        private void UnregisterCallbacks(INewPlayerControlsActions instance)
        {
            @AccelerationDeceleration.started -= instance.OnAccelerationDeceleration;
            @AccelerationDeceleration.performed -= instance.OnAccelerationDeceleration;
            @AccelerationDeceleration.canceled -= instance.OnAccelerationDeceleration;
            @Rotation.started -= instance.OnRotation;
            @Rotation.performed -= instance.OnRotation;
            @Rotation.canceled -= instance.OnRotation;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @AscendDescent.started -= instance.OnAscendDescent;
            @AscendDescent.performed -= instance.OnAscendDescent;
            @AscendDescent.canceled -= instance.OnAscendDescent;
            @PrimaryFire.started -= instance.OnPrimaryFire;
            @PrimaryFire.performed -= instance.OnPrimaryFire;
            @PrimaryFire.canceled -= instance.OnPrimaryFire;
            @ShootFlare.started -= instance.OnShootFlare;
            @ShootFlare.performed -= instance.OnShootFlare;
            @ShootFlare.canceled -= instance.OnShootFlare;
            @SelectLaserGun.started -= instance.OnSelectLaserGun;
            @SelectLaserGun.performed -= instance.OnSelectLaserGun;
            @SelectLaserGun.canceled -= instance.OnSelectLaserGun;
            @SelectVulcanGun.started -= instance.OnSelectVulcanGun;
            @SelectVulcanGun.performed -= instance.OnSelectVulcanGun;
            @SelectVulcanGun.canceled -= instance.OnSelectVulcanGun;
            @SelectConcussionMissile.started -= instance.OnSelectConcussionMissile;
            @SelectConcussionMissile.performed -= instance.OnSelectConcussionMissile;
            @SelectConcussionMissile.canceled -= instance.OnSelectConcussionMissile;
            @SelectHomingMissile.started -= instance.OnSelectHomingMissile;
            @SelectHomingMissile.performed -= instance.OnSelectHomingMissile;
            @SelectHomingMissile.canceled -= instance.OnSelectHomingMissile;
            @SecondaryFire.started -= instance.OnSecondaryFire;
            @SecondaryFire.performed -= instance.OnSecondaryFire;
            @SecondaryFire.canceled -= instance.OnSecondaryFire;
        }

        public void RemoveCallbacks(INewPlayerControlsActions instance)
        {
            if (m_Wrapper.m_NewPlayerControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(INewPlayerControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_NewPlayerControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_NewPlayerControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public NewPlayerControlsActions @NewPlayerControls => new NewPlayerControlsActions(this);

    // OldPlayerControls
    private readonly InputActionMap m_OldPlayerControls;
    private List<IOldPlayerControlsActions> m_OldPlayerControlsActionsCallbackInterfaces = new List<IOldPlayerControlsActions>();
    private readonly InputAction m_OldPlayerControls_AccelerationDeceleration;
    private readonly InputAction m_OldPlayerControls_Rotation;
    private readonly InputAction m_OldPlayerControls_Look;
    private readonly InputAction m_OldPlayerControls_PrimaryFire;
    private readonly InputAction m_OldPlayerControls_ShootFlare;
    private readonly InputAction m_OldPlayerControls_SelectLaserGun;
    private readonly InputAction m_OldPlayerControls_SelectVulkanGun;
    private readonly InputAction m_OldPlayerControls_SelectConcussionMissile;
    private readonly InputAction m_OldPlayerControls_SelectHomingMissile;
    private readonly InputAction m_OldPlayerControls_SecondaryFire;
    public struct OldPlayerControlsActions
    {
        private @PlayerControls m_Wrapper;
        public OldPlayerControlsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @AccelerationDeceleration => m_Wrapper.m_OldPlayerControls_AccelerationDeceleration;
        public InputAction @Rotation => m_Wrapper.m_OldPlayerControls_Rotation;
        public InputAction @Look => m_Wrapper.m_OldPlayerControls_Look;
        public InputAction @PrimaryFire => m_Wrapper.m_OldPlayerControls_PrimaryFire;
        public InputAction @ShootFlare => m_Wrapper.m_OldPlayerControls_ShootFlare;
        public InputAction @SelectLaserGun => m_Wrapper.m_OldPlayerControls_SelectLaserGun;
        public InputAction @SelectVulkanGun => m_Wrapper.m_OldPlayerControls_SelectVulkanGun;
        public InputAction @SelectConcussionMissile => m_Wrapper.m_OldPlayerControls_SelectConcussionMissile;
        public InputAction @SelectHomingMissile => m_Wrapper.m_OldPlayerControls_SelectHomingMissile;
        public InputAction @SecondaryFire => m_Wrapper.m_OldPlayerControls_SecondaryFire;
        public InputActionMap Get() { return m_Wrapper.m_OldPlayerControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OldPlayerControlsActions set) { return set.Get(); }
        public void AddCallbacks(IOldPlayerControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_OldPlayerControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_OldPlayerControlsActionsCallbackInterfaces.Add(instance);
            @AccelerationDeceleration.started += instance.OnAccelerationDeceleration;
            @AccelerationDeceleration.performed += instance.OnAccelerationDeceleration;
            @AccelerationDeceleration.canceled += instance.OnAccelerationDeceleration;
            @Rotation.started += instance.OnRotation;
            @Rotation.performed += instance.OnRotation;
            @Rotation.canceled += instance.OnRotation;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @PrimaryFire.started += instance.OnPrimaryFire;
            @PrimaryFire.performed += instance.OnPrimaryFire;
            @PrimaryFire.canceled += instance.OnPrimaryFire;
            @ShootFlare.started += instance.OnShootFlare;
            @ShootFlare.performed += instance.OnShootFlare;
            @ShootFlare.canceled += instance.OnShootFlare;
            @SelectLaserGun.started += instance.OnSelectLaserGun;
            @SelectLaserGun.performed += instance.OnSelectLaserGun;
            @SelectLaserGun.canceled += instance.OnSelectLaserGun;
            @SelectVulkanGun.started += instance.OnSelectVulkanGun;
            @SelectVulkanGun.performed += instance.OnSelectVulkanGun;
            @SelectVulkanGun.canceled += instance.OnSelectVulkanGun;
            @SelectConcussionMissile.started += instance.OnSelectConcussionMissile;
            @SelectConcussionMissile.performed += instance.OnSelectConcussionMissile;
            @SelectConcussionMissile.canceled += instance.OnSelectConcussionMissile;
            @SelectHomingMissile.started += instance.OnSelectHomingMissile;
            @SelectHomingMissile.performed += instance.OnSelectHomingMissile;
            @SelectHomingMissile.canceled += instance.OnSelectHomingMissile;
            @SecondaryFire.started += instance.OnSecondaryFire;
            @SecondaryFire.performed += instance.OnSecondaryFire;
            @SecondaryFire.canceled += instance.OnSecondaryFire;
        }

        private void UnregisterCallbacks(IOldPlayerControlsActions instance)
        {
            @AccelerationDeceleration.started -= instance.OnAccelerationDeceleration;
            @AccelerationDeceleration.performed -= instance.OnAccelerationDeceleration;
            @AccelerationDeceleration.canceled -= instance.OnAccelerationDeceleration;
            @Rotation.started -= instance.OnRotation;
            @Rotation.performed -= instance.OnRotation;
            @Rotation.canceled -= instance.OnRotation;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @PrimaryFire.started -= instance.OnPrimaryFire;
            @PrimaryFire.performed -= instance.OnPrimaryFire;
            @PrimaryFire.canceled -= instance.OnPrimaryFire;
            @ShootFlare.started -= instance.OnShootFlare;
            @ShootFlare.performed -= instance.OnShootFlare;
            @ShootFlare.canceled -= instance.OnShootFlare;
            @SelectLaserGun.started -= instance.OnSelectLaserGun;
            @SelectLaserGun.performed -= instance.OnSelectLaserGun;
            @SelectLaserGun.canceled -= instance.OnSelectLaserGun;
            @SelectVulkanGun.started -= instance.OnSelectVulkanGun;
            @SelectVulkanGun.performed -= instance.OnSelectVulkanGun;
            @SelectVulkanGun.canceled -= instance.OnSelectVulkanGun;
            @SelectConcussionMissile.started -= instance.OnSelectConcussionMissile;
            @SelectConcussionMissile.performed -= instance.OnSelectConcussionMissile;
            @SelectConcussionMissile.canceled -= instance.OnSelectConcussionMissile;
            @SelectHomingMissile.started -= instance.OnSelectHomingMissile;
            @SelectHomingMissile.performed -= instance.OnSelectHomingMissile;
            @SelectHomingMissile.canceled -= instance.OnSelectHomingMissile;
            @SecondaryFire.started -= instance.OnSecondaryFire;
            @SecondaryFire.performed -= instance.OnSecondaryFire;
            @SecondaryFire.canceled -= instance.OnSecondaryFire;
        }

        public void RemoveCallbacks(IOldPlayerControlsActions instance)
        {
            if (m_Wrapper.m_OldPlayerControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IOldPlayerControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_OldPlayerControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_OldPlayerControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public OldPlayerControlsActions @OldPlayerControls => new OldPlayerControlsActions(this);
    public interface INewPlayerControlsActions
    {
        void OnAccelerationDeceleration(InputAction.CallbackContext context);
        void OnRotation(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnAscendDescent(InputAction.CallbackContext context);
        void OnPrimaryFire(InputAction.CallbackContext context);
        void OnShootFlare(InputAction.CallbackContext context);
        void OnSelectLaserGun(InputAction.CallbackContext context);
        void OnSelectVulcanGun(InputAction.CallbackContext context);
        void OnSelectConcussionMissile(InputAction.CallbackContext context);
        void OnSelectHomingMissile(InputAction.CallbackContext context);
        void OnSecondaryFire(InputAction.CallbackContext context);
    }
    public interface IOldPlayerControlsActions
    {
        void OnAccelerationDeceleration(InputAction.CallbackContext context);
        void OnRotation(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnPrimaryFire(InputAction.CallbackContext context);
        void OnShootFlare(InputAction.CallbackContext context);
        void OnSelectLaserGun(InputAction.CallbackContext context);
        void OnSelectVulkanGun(InputAction.CallbackContext context);
        void OnSelectConcussionMissile(InputAction.CallbackContext context);
        void OnSelectHomingMissile(InputAction.CallbackContext context);
        void OnSecondaryFire(InputAction.CallbackContext context);
    }
}
